# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 911)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnImprtSettings = QtWidgets.QPushButton(self.centralWidget)
        self.btnImprtSettings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnImprtSettings.setObjectName("btnImprtSettings")
        self.gridLayout.addWidget(self.btnImprtSettings, 1, 0, 1, 1)
        self.btnRepeatStep = QtWidgets.QPushButton(self.centralWidget)
        self.btnRepeatStep.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnRepeatStep.setObjectName("btnRepeatStep")
        self.gridLayout.addWidget(self.btnRepeatStep, 3, 0, 1, 1)
        self.btnRunNextStep = QtWidgets.QPushButton(self.centralWidget)
        self.btnRunNextStep.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnRunNextStep.setObjectName("btnRunNextStep")
        self.gridLayout.addWidget(self.btnRunNextStep, 4, 0, 1, 1)
        self.btnStartAnalysis = QtWidgets.QPushButton(self.centralWidget)
        self.btnStartAnalysis.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnStartAnalysis.setObjectName("btnStartAnalysis")
        self.gridLayout.addWidget(self.btnStartAnalysis, 5, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 2)
        self.LogsTextBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.LogsTextBrowser.setMaximumSize(QtCore.QSize(16777215, 1111))
        self.LogsTextBrowser.setObjectName("LogsTextBrowser")
        self.gridLayout.addWidget(self.LogsTextBrowser, 1, 1, 5, 1)
        self.btnSaveSettings = QtWidgets.QPushButton(self.centralWidget)
        self.btnSaveSettings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnSaveSettings.setObjectName("btnSaveSettings")
        self.gridLayout.addWidget(self.btnSaveSettings, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(11111111, 11111111))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.gen_settings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_settings.sizePolicy().hasHeightForWidth())
        self.gen_settings.setSizePolicy(sizePolicy)
        self.gen_settings.setObjectName("gen_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gen_settings)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.gen_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.helpText = QtWidgets.QTextEdit(self.gen_settings)
        self.helpText.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText.setObjectName("helpText")
        self.gridLayout_3.addWidget(self.helpText, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gen_settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnCpPipeFile = QtWidgets.QToolButton(self.groupBox_2)
        self.btnCpPipeFile.setObjectName("btnCpPipeFile")
        self.gridLayout_8.addWidget(self.btnCpPipeFile, 6, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_8.addWidget(self.pushButton_15, 6, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 6, 0, 1, 1)
        self.lineEditCPpipeFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditCPpipeFile.setObjectName("lineEditCPpipeFile")
        self.gridLayout_8.addWidget(self.lineEditCPpipeFile, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.lineEditCompositeImg = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditCompositeImg.setObjectName("lineEditCompositeImg")
        self.gridLayout_8.addWidget(self.lineEditCompositeImg, 5, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.btnStitchedPostMDapiImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnStitchedPostMDapiImg.setObjectName("btnStitchedPostMDapiImg")
        self.gridLayout_8.addWidget(self.btnStitchedPostMDapiImg, 3, 2, 1, 1)
        self.btnStitchedPreMSampleImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnStitchedPreMSampleImg.setObjectName("btnStitchedPreMSampleImg")
        self.gridLayout_8.addWidget(self.btnStitchedPreMSampleImg, 4, 2, 1, 1)
        self.lineEditStitPostMDapiImage = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditStitPostMDapiImage.setObjectName("lineEditStitPostMDapiImage")
        self.gridLayout_8.addWidget(self.lineEditStitPostMDapiImage, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_8.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 5, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_8.addWidget(self.pushButton_12, 5, 3, 1, 1)
        self.btnStitchedPreMDapiImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnStitchedPreMDapiImg.setObjectName("btnStitchedPreMDapiImg")
        self.gridLayout_8.addWidget(self.btnStitchedPreMDapiImg, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 3, 0, 1, 1)
        self.lineEditStitPreMDapiImage = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditStitPreMDapiImage.setObjectName("lineEditStitPreMDapiImage")
        self.gridLayout_8.addWidget(self.lineEditStitPreMDapiImage, 2, 1, 1, 1)
        self.btnStitchedPreMBfImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnStitchedPreMBfImg.setObjectName("btnStitchedPreMBfImg")
        self.gridLayout_8.addWidget(self.btnStitchedPreMBfImg, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.lineEditStitPreMSampleImage = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditStitPreMSampleImage.setObjectName("lineEditStitPreMSampleImage")
        self.gridLayout_8.addWidget(self.lineEditStitPreMSampleImage, 4, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_8.addWidget(self.pushButton_14, 3, 3, 1, 1)
        self.btnCompositeImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnCompositeImg.setObjectName("btnCompositeImg")
        self.gridLayout_8.addWidget(self.btnCompositeImg, 5, 2, 1, 1)
        self.lineEditStitchedPostMImage = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditStitchedPostMImage.setObjectName("lineEditStitchedPostMImage")
        self.gridLayout_8.addWidget(self.lineEditStitchedPostMImage, 1, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_8.addWidget(self.pushButton_13, 4, 3, 1, 1)
        self.btnStitchedPostMBfImg = QtWidgets.QToolButton(self.groupBox_2)
        self.btnStitchedPostMBfImg.setObjectName("btnStitchedPostMBfImg")
        self.gridLayout_8.addWidget(self.btnStitchedPostMBfImg, 1, 2, 1, 1)
        self.lineEditStitchedPreMImage = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditStitchedPreMImage.setObjectName("lineEditStitchedPreMImage")
        self.gridLayout_8.addWidget(self.lineEditStitchedPreMImage, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gen_settings)
        self.groupBox.setMaximumSize(QtCore.QSize(661, 140))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditMainFolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditMainFolder.setObjectName("lineEditMainFolder")
        self.gridLayout_2.addWidget(self.lineEditMainFolder, 0, 1, 1, 1)
        self.btnCellProfiler = QtWidgets.QToolButton(self.groupBox)
        self.btnCellProfiler.setObjectName("btnCellProfiler")
        self.gridLayout_2.addWidget(self.btnCellProfiler, 2, 2, 1, 1)
        self.btnPython = QtWidgets.QToolButton(self.groupBox)
        self.btnPython.setObjectName("btnPython")
        self.gridLayout_2.addWidget(self.btnPython, 1, 2, 1, 1)
        self.btnMainFolder = QtWidgets.QToolButton(self.groupBox)
        self.btnMainFolder.setObjectName("btnMainFolder")
        self.gridLayout_2.addWidget(self.btnMainFolder, 0, 2, 1, 1)
        self.lineEditCellProfiler = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCellProfiler.setObjectName("lineEditCellProfiler")
        self.gridLayout_2.addWidget(self.lineEditCellProfiler, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditPythonPath = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditPythonPath.setObjectName("lineEditPythonPath")
        self.gridLayout_2.addWidget(self.lineEditPythonPath, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gen_settings)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnUdpFile = QtWidgets.QToolButton(self.groupBox_3)
        self.btnUdpFile.setObjectName("btnUdpFile")
        self.gridLayout_6.addWidget(self.btnUdpFile, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 4, 1, 1)
        self.btnImzMLFilename = QtWidgets.QToolButton(self.groupBox_3)
        self.btnImzMLFilename.setObjectName("btnImzMLFilename")
        self.gridLayout_6.addWidget(self.btnImzMLFilename, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 2)
        self.lineEditMetadata = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditMetadata.setObjectName("lineEditMetadata")
        self.gridLayout_6.addWidget(self.lineEditMetadata, 2, 2, 1, 1)
        self.btnMALDImetadata = QtWidgets.QToolButton(self.groupBox_3)
        self.btnMALDImetadata.setObjectName("btnMALDImetadata")
        self.gridLayout_6.addWidget(self.btnMALDImetadata, 2, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 2, 4, 1, 1)
        self.lineEditimzMLName = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditimzMLName.setObjectName("lineEditimzMLName")
        self.gridLayout_6.addWidget(self.lineEditimzMLName, 1, 2, 1, 1)
        self.lineEditUdpFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditUdpFile.setObjectName("lineEditUdpFile")
        self.gridLayout_6.addWidget(self.lineEditUdpFile, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.gen_settings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEditMSLogin = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditMSLogin.setObjectName("lineEditMSLogin")
        self.gridLayout_7.addWidget(self.lineEditMSLogin, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEditMSPass = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditMSPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditMSPass.setObjectName("lineEditMSPass")
        self.gridLayout_7.addWidget(self.lineEditMSPass, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEditMSDb = QtWidgets.QListWidget(self.groupBox_4)
        self.lineEditMSDb.setObjectName("lineEditMSDb")
        item = QtWidgets.QListWidgetItem()
        self.lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lineEditMSDb.addItem(item)
        self.gridLayout_7.addWidget(self.lineEditMSDb, 2, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 3, 0, 1, 1)
        self.comboBoxFdr = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxFdr.setObjectName("comboBoxFdr")
        self.comboBoxFdr.addItem("")
        self.comboBoxFdr.addItem("")
        self.comboBoxFdr.addItem("")
        self.gridLayout_7.addWidget(self.comboBoxFdr, 3, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_7.addWidget(self.pushButton_11, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.gen_settings, "")
        self.amf_tab = QtWidgets.QWidget()
        self.amf_tab.setObjectName("amf_tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.amf_tab)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.helpText_2 = QtWidgets.QTextEdit(self.amf_tab)
        self.helpText_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_2.setObjectName("helpText_2")
        self.gridLayout_4.addWidget(self.helpText_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.amf_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.amf_tab)
        self.widget_2.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 100))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_12.addWidget(self.comboBox, 0, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(300, 100))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.tab1_sbFftIters = QtWidgets.QSpinBox(self.groupBox_6)
        self.tab1_sbFftIters.setMaximum(100)
        self.tab1_sbFftIters.setProperty("value", 20)
        self.tab1_sbFftIters.setObjectName("tab1_sbFftIters")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tab1_sbFftIters)
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.tab1_sbFftGblurSigma = QtWidgets.QSpinBox(self.groupBox_6)
        self.tab1_sbFftGblurSigma.setMinimum(1)
        self.tab1_sbFftGblurSigma.setMaximum(50)
        self.tab1_sbFftGblurSigma.setObjectName("tab1_sbFftGblurSigma")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tab1_sbFftGblurSigma)
        self.gridLayout_11.addLayout(self.formLayout, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.groupBox_6)
        self.gridLayout_4.addWidget(self.widget_2, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.amf_tab, "")
        self.fids_tab = QtWidgets.QWidget()
        self.fids_tab.setObjectName("fids_tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.fids_tab)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.helpText_3 = QtWidgets.QTextEdit(self.fids_tab)
        self.helpText_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_3.setObjectName("helpText_3")
        self.gridLayout_9.addWidget(self.helpText_3, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.fids_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.fids_tab)
        self.widget_3.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_9.addWidget(self.widget_3, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fids_tab, "")
        self.reg_tab = QtWidgets.QWidget()
        self.reg_tab.setObjectName("reg_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.reg_tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.helpText_4 = QtWidgets.QTextEdit(self.reg_tab)
        self.helpText_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_4.setObjectName("helpText_4")
        self.gridLayout_15.addWidget(self.helpText_4, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.reg_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.reg_tab)
        self.widget_4.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_15.addWidget(self.widget_4, 2, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_15)
        self.tabWidget.addTab(self.reg_tab, "")
        self.grab_ms_data_tab = QtWidgets.QWidget()
        self.grab_ms_data_tab.setObjectName("grab_ms_data_tab")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.grab_ms_data_tab)
        self.verticalLayout_30.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_30.setSpacing(6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_72 = QtWidgets.QLabel(self.grab_ms_data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_29.addWidget(self.label_72)
        self.helpText_15 = QtWidgets.QTextEdit(self.grab_ms_data_tab)
        self.helpText_15.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_15.setObjectName("helpText_15")
        self.verticalLayout_29.addWidget(self.helpText_15)
        self.widget_13 = QtWidgets.QWidget(self.grab_ms_data_tab)
        self.widget_13.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_13.setObjectName("widget_13")
        self.groupBox_19 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 10, 283, 129))
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_44.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_44.setSpacing(6)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_73 = QtWidgets.QLabel(self.groupBox_19)
        self.label_73.setObjectName("label_73")
        self.gridLayout_44.addWidget(self.label_73, 0, 0, 1, 1)
        self.lineEditMSLogin_4 = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEditMSLogin_4.setObjectName("lineEditMSLogin_4")
        self.gridLayout_44.addWidget(self.lineEditMSLogin_4, 0, 1, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_44.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_44.addWidget(self.pushButton_44, 0, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_19)
        self.label_74.setObjectName("label_74")
        self.gridLayout_44.addWidget(self.label_74, 1, 0, 1, 1)
        self.lineEditMSPass_4 = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEditMSPass_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditMSPass_4.setObjectName("lineEditMSPass_4")
        self.gridLayout_44.addWidget(self.lineEditMSPass_4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_44.addWidget(self.pushButton, 2, 0, 1, 2)
        self.groupBox_20 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 150, 318, 294))
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_45.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_45.setSpacing(6)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_75 = QtWidgets.QLabel(self.groupBox_20)
        self.label_75.setObjectName("label_75")
        self.gridLayout_45.addWidget(self.label_75, 0, 0, 1, 2)
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_46.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_45.addWidget(self.pushButton_46, 0, 2, 1, 1)
        self.lineEditMSDb_4 = QtWidgets.QListWidget(self.groupBox_20)
        self.lineEditMSDb_4.setObjectName("lineEditMSDb_4")
        item = QtWidgets.QListWidgetItem()
        self.lineEditMSDb_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lineEditMSDb_4.addItem(item)
        self.gridLayout_45.addWidget(self.lineEditMSDb_4, 1, 0, 1, 2)
        self.label_76 = QtWidgets.QLabel(self.groupBox_20)
        self.label_76.setObjectName("label_76")
        self.gridLayout_45.addWidget(self.label_76, 2, 0, 1, 1)
        self.comboBoxFdr_4 = QtWidgets.QComboBox(self.groupBox_20)
        self.comboBoxFdr_4.setObjectName("comboBoxFdr_4")
        self.comboBoxFdr_4.addItem("")
        self.comboBoxFdr_4.addItem("")
        self.comboBoxFdr_4.addItem("")
        self.gridLayout_45.addWidget(self.comboBoxFdr_4, 2, 1, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_47.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_45.addWidget(self.pushButton_47, 2, 2, 1, 1)
        self.verticalLayout_29.addWidget(self.widget_13)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.tabWidget.addTab(self.grab_ms_data_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.gridLayout_14.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1093, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuSd = QtWidgets.QMenu(self.menuBar)
        self.menuSd.setObjectName("menuSd")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport_settings = QtWidgets.QAction(MainWindow)
        self.actionImport_settings.setObjectName("actionImport_settings")
        self.menuSd.addAction(self.actionImport_settings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuSd.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "spaceM 0.1"))
        self.btnImprtSettings.setText(_translate("MainWindow", "Import settings"))
        self.btnRepeatStep.setText(_translate("MainWindow", "Repeat previous step"))
        self.btnRunNextStep.setText(_translate("MainWindow", "Run next step"))
        self.btnStartAnalysis.setText(_translate("MainWindow", "Run pipeline"))
        self.LogsTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logs</p></body></html>"))
        self.btnSaveSettings.setText(_translate("MainWindow", "Save settings"))
        self.label.setText(_translate("MainWindow", "Help:"))
        self.helpText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is an example text that will be substituted with a custom step dependent explanotary information. For general setting, user has to provide all necessary paths to Main folder to where to store the output files, path to Python interpreter(ver&gt;3), and select stitched image with cell Profiler installed path.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pre/Post MALDI images"))
        self.btnCpPipeFile.setText(_translate("MainWindow", "..."))
        self.pushButton_15.setText(_translate("MainWindow", "?"))
        self.label_19.setText(_translate("MainWindow", "(Optional) Cellprofiler pipeline file:"))
        self.label_17.setText(_translate("MainWindow", "Pre MALDI fluorescent (DAPI) image:"))
        self.pushButton_6.setText(_translate("MainWindow", "?"))
        self.btnStitchedPostMDapiImg.setText(_translate("MainWindow", "..."))
        self.btnStitchedPreMSampleImg.setText(_translate("MainWindow", "..."))
        self.pushButton_3.setText(_translate("MainWindow", "?"))
        self.label_8.setText(_translate("MainWindow", "Stitched Pre MALDI brightfield image:"))
        self.label_18.setText(_translate("MainWindow", "Composite.png file:"))
        self.pushButton_12.setText(_translate("MainWindow", "?"))
        self.btnStitchedPreMDapiImg.setText(_translate("MainWindow", "..."))
        self.label_15.setText(_translate("MainWindow", "Post MALDI fluorescent  (DAPI) image:"))
        self.btnStitchedPreMBfImg.setText(_translate("MainWindow", "..."))
        self.label_16.setText(_translate("MainWindow", "(Optional) Pre MALDI fluorescent image:"))
        self.label_11.setText(_translate("MainWindow", "Stitched Post MALDI brightfield mage:"))
        self.pushButton_2.setText(_translate("MainWindow", "?"))
        self.pushButton_14.setText(_translate("MainWindow", "?"))
        self.btnCompositeImg.setText(_translate("MainWindow", "..."))
        self.pushButton_13.setText(_translate("MainWindow", "?"))
        self.btnStitchedPostMBfImg.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "General settings"))
        self.label_6.setText(_translate("MainWindow", "Cell Profiler path(Windows only):"))
        self.label_3.setText(_translate("MainWindow", "Main Folder:"))
        self.btnCellProfiler.setText(_translate("MainWindow", "..."))
        self.btnPython.setText(_translate("MainWindow", "..."))
        self.btnMainFolder.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Python interpreter:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "MALDI data"))
        self.btnUdpFile.setText(_translate("MainWindow", "..."))
        self.pushButton_4.setText(_translate("MainWindow", "?"))
        self.btnImzMLFilename.setText(_translate("MainWindow", "..."))
        self.pushButton_5.setText(_translate("MainWindow", "?"))
        self.label_12.setText(_translate("MainWindow", "MALDI Metadata file:"))
        self.btnMALDImetadata.setText(_translate("MainWindow", "..."))
        self.pushButton_7.setText(_translate("MainWindow", "?"))
        self.label_5.setText(_translate("MainWindow", "imzML filename"))
        self.label_7.setText(_translate("MainWindow", "UDP file:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Metaspace data"))
        self.label_9.setText(_translate("MainWindow", "Login:"))
        self.pushButton_8.setText(_translate("MainWindow", "?"))
        self.label_10.setText(_translate("MainWindow", "Password:"))
        self.pushButton_9.setText(_translate("MainWindow", "?"))
        self.label_13.setText(_translate("MainWindow", "Database:"))
        __sortingEnabled = self.lineEditMSDb.isSortingEnabled()
        self.lineEditMSDb.setSortingEnabled(False)
        item = self.lineEditMSDb.item(0)
        item.setText(_translate("MainWindow", "HMDB-v4"))
        item = self.lineEditMSDb.item(1)
        item.setText(_translate("MainWindow", "Chebi-2018-1"))
        self.lineEditMSDb.setSortingEnabled(__sortingEnabled)
        self.pushButton_10.setText(_translate("MainWindow", "?"))
        self.label_14.setText(_translate("MainWindow", "FDR:"))
        self.comboBoxFdr.setItemText(0, _translate("MainWindow", "10%"))
        self.comboBoxFdr.setItemText(1, _translate("MainWindow", "20%"))
        self.comboBoxFdr.setItemText(2, _translate("MainWindow", "50%"))
        self.pushButton_11.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gen_settings), _translate("MainWindow", "General settings"))
        self.helpText_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ablation mark finder is the first step to find region with the ablation marks that is based on fast Fouirer transformation, image blurring in the frequency space and its dilation to get to know what are the parameters play with them and check the output.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Help:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Matrix preparation type"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DHB"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DAN"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Fast fourier transformation settings"))
        self.label_20.setText(_translate("MainWindow", "Iterations:"))
        self.label_21.setText(_translate("MainWindow", "Gaussian blur sigma:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.amf_tab), _translate("MainWindow", "Ablation mark finder"))
        self.helpText_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Help:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fids_tab), _translate("MainWindow", "Fiducials search"))
        self.helpText_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Help:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reg_tab), _translate("MainWindow", "Registration"))
        self.label_72.setText(_translate("MainWindow", "Help:"))
        self.helpText_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Metaspace login"))
        self.label_73.setText(_translate("MainWindow", "Login:"))
        self.pushButton_44.setText(_translate("MainWindow", "?"))
        self.label_74.setText(_translate("MainWindow", "Password:"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Pulled data settings"))
        self.label_75.setText(_translate("MainWindow", "Database:"))
        self.pushButton_46.setText(_translate("MainWindow", "?"))
        __sortingEnabled = self.lineEditMSDb_4.isSortingEnabled()
        self.lineEditMSDb_4.setSortingEnabled(False)
        item = self.lineEditMSDb_4.item(0)
        item.setText(_translate("MainWindow", "HMDB-v4"))
        item = self.lineEditMSDb_4.item(1)
        item.setText(_translate("MainWindow", "Chebi-2018-1"))
        self.lineEditMSDb_4.setSortingEnabled(__sortingEnabled)
        self.label_76.setText(_translate("MainWindow", "FDR:"))
        self.comboBoxFdr_4.setItemText(0, _translate("MainWindow", "10%"))
        self.comboBoxFdr_4.setItemText(1, _translate("MainWindow", "20%"))
        self.comboBoxFdr_4.setItemText(2, _translate("MainWindow", "50%"))
        self.pushButton_47.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.grab_ms_data_tab), _translate("MainWindow", "Grabbing MS data"))
        self.menuSd.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionImport_settings.setText(_translate("MainWindow", "Import settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

