# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/renat/EMBL/spaceM_Luca/linux/1c_gui_complete/qt_files/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 911)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRepeatStep = QtWidgets.QPushButton(self.centralWidget)
        self.btnRepeatStep.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnRepeatStep.setObjectName("btnRepeatStep")
        self.gridLayout.addWidget(self.btnRepeatStep, 3, 0, 1, 1)
        self.btnImprtSettings = QtWidgets.QPushButton(self.centralWidget)
        self.btnImprtSettings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnImprtSettings.setObjectName("btnImprtSettings")
        self.gridLayout.addWidget(self.btnImprtSettings, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(11111111, 11111111))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.gen_settings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_settings.sizePolicy().hasHeightForWidth())
        self.gen_settings.setSizePolicy(sizePolicy)
        self.gen_settings.setObjectName("gen_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gen_settings)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.gen_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.helpText = QtWidgets.QTextEdit(self.gen_settings)
        self.helpText.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText.setObjectName("helpText")
        self.gridLayout_3.addWidget(self.helpText, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gen_settings)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMaximumSize(QtCore.QSize(555555, 55555))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_49.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_49.setSpacing(6)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditMainFolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditMainFolder.setObjectName("lineEditMainFolder")
        self.gridLayout_2.addWidget(self.lineEditMainFolder, 0, 2, 1, 1)
        self.btnCellProfiler = QtWidgets.QToolButton(self.groupBox)
        self.btnCellProfiler.setObjectName("btnCellProfiler")
        self.gridLayout_2.addWidget(self.btnCellProfiler, 2, 3, 1, 1)
        self.btnPython = QtWidgets.QToolButton(self.groupBox)
        self.btnPython.setObjectName("btnPython")
        self.gridLayout_2.addWidget(self.btnPython, 1, 3, 1, 1)
        self.lineEditCellProfiler = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCellProfiler.setObjectName("lineEditCellProfiler")
        self.gridLayout_2.addWidget(self.lineEditCellProfiler, 2, 2, 1, 1)
        self.btnMainFolder = QtWidgets.QToolButton(self.groupBox)
        self.btnMainFolder.setObjectName("btnMainFolder")
        self.gridLayout_2.addWidget(self.btnMainFolder, 0, 3, 1, 1)
        self.lineEditPythonPath = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditPythonPath.setObjectName("lineEditPythonPath")
        self.gridLayout_2.addWidget(self.lineEditPythonPath, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 2, 4, 1, 1)
        self.gridLayout_49.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.groupBox_2.raise_()
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(5555555, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_50.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_50.setSpacing(6)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnStitchedPostMBfImg = QtWidgets.QToolButton(self.groupBox_6)
        self.btnStitchedPostMBfImg.setObjectName("btnStitchedPostMBfImg")
        self.gridLayout_8.addWidget(self.btnStitchedPostMBfImg, 1, 3, 1, 1)
        self.btnStitchedPreMBfImg = QtWidgets.QToolButton(self.groupBox_6)
        self.btnStitchedPreMBfImg.setObjectName("btnStitchedPreMBfImg")
        self.gridLayout_8.addWidget(self.btnStitchedPreMBfImg, 0, 3, 1, 1)
        self.lineEditStitchedPostMImage = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditStitchedPostMImage.setObjectName("lineEditStitchedPostMImage")
        self.gridLayout_8.addWidget(self.lineEditStitchedPostMImage, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEditStitchedPreMImage = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditStitchedPreMImage.setObjectName("lineEditStitchedPreMImage")
        self.gridLayout_8.addWidget(self.lineEditStitchedPreMImage, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_8.addWidget(self.pushButton_3, 1, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_50.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_51.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_51.setSpacing(6)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        self.btnMALDImetadata = QtWidgets.QToolButton(self.groupBox_3)
        self.btnMALDImetadata.setObjectName("btnMALDImetadata")
        self.gridLayout_6.addWidget(self.btnMALDImetadata, 1, 4, 1, 1)
        self.lineEditMetadata = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditMetadata.setObjectName("lineEditMetadata")
        self.gridLayout_6.addWidget(self.lineEditMetadata, 1, 3, 1, 1)
        self.lineEditUdpFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditUdpFile.setObjectName("lineEditUdpFile")
        self.gridLayout_6.addWidget(self.lineEditUdpFile, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 2)
        self.btnUdpFile = QtWidgets.QToolButton(self.groupBox_3)
        self.btnUdpFile.setObjectName("btnUdpFile")
        self.gridLayout_6.addWidget(self.btnUdpFile, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 1, 5, 1, 1)
        self.gridLayout_51.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.gen_settings, "")
        self.amf_tab = QtWidgets.QWidget()
        self.amf_tab.setObjectName("amf_tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.amf_tab)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.helpText_2 = QtWidgets.QTextEdit(self.amf_tab)
        self.helpText_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_2.setObjectName("helpText_2")
        self.gridLayout_4.addWidget(self.helpText_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.amf_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.amf_tab)
        self.widget_2.setMaximumSize(QtCore.QSize(5555555, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_54.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_54.setSpacing(6)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.groupBox_22 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_22)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.tab_amf_markSize = QtWidgets.QSpinBox(self.groupBox_22)
        self.tab_amf_markSize.setProperty("value", 15)
        self.tab_amf_markSize.setObjectName("tab_amf_markSize")
        self.gridLayout_7.addWidget(self.tab_amf_markSize, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_54.addWidget(self.groupBox_22, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_55.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_55.setSpacing(6)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.tab_amf_gbFluoCh = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_amf_gbFluoCh.sizePolicy().hasHeightForWidth())
        self.tab_amf_gbFluoCh.setSizePolicy(sizePolicy)
        self.tab_amf_gbFluoCh.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab_amf_gbFluoCh.setObjectName("tab_amf_gbFluoCh")
        self.gridLayout_56 = QtWidgets.QGridLayout(self.tab_amf_gbFluoCh)
        self.gridLayout_56.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_56.setSpacing(6)
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tab_amf_FluoCh = QtWidgets.QLineEdit(self.tab_amf_gbFluoCh)
        self.tab_amf_FluoCh.setObjectName("tab_amf_FluoCh")
        self.gridLayout_12.addWidget(self.tab_amf_FluoCh, 1, 0, 1, 1)
        self.tab_amf_btnFluoCh = QtWidgets.QToolButton(self.tab_amf_gbFluoCh)
        self.tab_amf_btnFluoCh.setObjectName("tab_amf_btnFluoCh")
        self.gridLayout_12.addWidget(self.tab_amf_btnFluoCh, 1, 1, 1, 1)
        self.tab_amf_labelFluoCh = QtWidgets.QLabel(self.tab_amf_gbFluoCh)
        self.tab_amf_labelFluoCh.setObjectName("tab_amf_labelFluoCh")
        self.gridLayout_12.addWidget(self.tab_amf_labelFluoCh, 0, 0, 1, 1)
        self.gridLayout_56.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tab_amf_FluoCh.raise_()
        self.tab_amf_FluoCh.raise_()
        self.tab_amf_FluoCh.raise_()
        self.tab_amf_FluoCh.raise_()
        self.tab_amf_labelFluoCh.raise_()
        self.tab_amf_btnFluoCh.raise_()
        self.gridLayout_55.addWidget(self.tab_amf_gbFluoCh, 1, 0, 1, 1)
        self.tab_amf_cbMatrix = QtWidgets.QComboBox(self.groupBox_5)
        self.tab_amf_cbMatrix.setObjectName("tab_amf_cbMatrix")
        self.tab_amf_cbMatrix.addItem("")
        self.tab_amf_cbMatrix.addItem("")
        self.gridLayout_55.addWidget(self.tab_amf_cbMatrix, 0, 0, 1, 1)
        self.tab_amf_cbMatrix.raise_()
        self.tab_amf_gbFluoCh.raise_()
        self.gridLayout_54.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tab_amf_amDetect = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_amf_amDetect.sizePolicy().hasHeightForWidth())
        self.tab_amf_amDetect.setSizePolicy(sizePolicy)
        self.tab_amf_amDetect.setMaximumSize(QtCore.QSize(5555555, 200))
        self.tab_amf_amDetect.setObjectName("tab_amf_amDetect")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_amf_amDetect)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_amf_ifftImgPath = QtWidgets.QLineEdit(self.tab_amf_amDetect)
        self.tab_amf_ifftImgPath.setObjectName("tab_amf_ifftImgPath")
        self.horizontalLayout_3.addWidget(self.tab_amf_ifftImgPath)
        self.tab_amf_btniFFTimg = QtWidgets.QToolButton(self.tab_amf_amDetect)
        self.tab_amf_btniFFTimg.setObjectName("tab_amf_btniFFTimg")
        self.horizontalLayout_3.addWidget(self.tab_amf_btniFFTimg)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_amf_amDetect)
        self.pushButton_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.tab_amf_autoFftRb = QtWidgets.QRadioButton(self.tab_amf_amDetect)
        self.tab_amf_autoFftRb.setChecked(True)
        self.tab_amf_autoFftRb.setObjectName("tab_amf_autoFftRb")
        self.gridLayout_14.addWidget(self.tab_amf_autoFftRb, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_amf_amDetect)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 1, 0, 1, 1)
        self.tab_amf_sbFftIters = QtWidgets.QSpinBox(self.tab_amf_amDetect)
        self.tab_amf_sbFftIters.setMaximum(100)
        self.tab_amf_sbFftIters.setProperty("value", 20)
        self.tab_amf_sbFftIters.setObjectName("tab_amf_sbFftIters")
        self.gridLayout_14.addWidget(self.tab_amf_sbFftIters, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_amf_amDetect)
        self.label_21.setObjectName("label_21")
        self.gridLayout_14.addWidget(self.label_21, 2, 0, 1, 1)
        self.tab_amf_sbFftGblurSigma = QtWidgets.QSpinBox(self.tab_amf_amDetect)
        self.tab_amf_sbFftGblurSigma.setMinimum(1)
        self.tab_amf_sbFftGblurSigma.setMaximum(50)
        self.tab_amf_sbFftGblurSigma.setProperty("value", 10)
        self.tab_amf_sbFftGblurSigma.setObjectName("tab_amf_sbFftGblurSigma")
        self.gridLayout_14.addWidget(self.tab_amf_sbFftGblurSigma, 2, 1, 1, 1)
        self.tab_amf_manFftRb = QtWidgets.QRadioButton(self.tab_amf_amDetect)
        self.tab_amf_manFftRb.setObjectName("tab_amf_manFftRb")
        self.gridLayout_14.addWidget(self.tab_amf_manFftRb, 3, 0, 1, 2)
        self.gridLayout_54.addWidget(self.tab_amf_amDetect, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_54.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.amf_tab, "")
        self.fids_tab = QtWidgets.QWidget()
        self.fids_tab.setObjectName("fids_tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.fids_tab)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.helpText_3 = QtWidgets.QTextEdit(self.fids_tab)
        self.helpText_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_3.setObjectName("helpText_3")
        self.gridLayout_9.addWidget(self.helpText_3, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.fids_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.fids_tab)
        self.widget_3.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_9.addWidget(self.widget_3, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fids_tab, "")
        self.reg_tab = QtWidgets.QWidget()
        self.reg_tab.setObjectName("reg_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.reg_tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.helpText_4 = QtWidgets.QTextEdit(self.reg_tab)
        self.helpText_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_4.setObjectName("helpText_4")
        self.gridLayout_15.addWidget(self.helpText_4, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.reg_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.reg_tab)
        self.widget_4.setMaximumSize(QtCore.QSize(1039, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_15.addWidget(self.widget_4, 2, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_15)
        self.tabWidget.addTab(self.reg_tab, "")
        self.grab_ms_data_tab = QtWidgets.QWidget()
        self.grab_ms_data_tab.setObjectName("grab_ms_data_tab")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.grab_ms_data_tab)
        self.verticalLayout_30.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_30.setSpacing(6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_72 = QtWidgets.QLabel(self.grab_ms_data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_29.addWidget(self.label_72)
        self.helpText_15 = QtWidgets.QTextEdit(self.grab_ms_data_tab)
        self.helpText_15.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_15.setObjectName("helpText_15")
        self.verticalLayout_29.addWidget(self.helpText_15)
        self.widget_13 = QtWidgets.QWidget(self.grab_ms_data_tab)
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_52.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_52.setSpacing(6)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.groupBox_19 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_19.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_44.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_44.setSpacing(6)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_44.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_44.addWidget(self.pushButton_44, 1, 2, 1, 1)
        self.tab_gms_lineEditMSPass = QtWidgets.QLineEdit(self.groupBox_19)
        self.tab_gms_lineEditMSPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tab_gms_lineEditMSPass.setObjectName("tab_gms_lineEditMSPass")
        self.gridLayout_44.addWidget(self.tab_gms_lineEditMSPass, 2, 1, 1, 1)
        self.tab_gms_lineEditMSLogin = QtWidgets.QLineEdit(self.groupBox_19)
        self.tab_gms_lineEditMSLogin.setObjectName("tab_gms_lineEditMSLogin")
        self.gridLayout_44.addWidget(self.tab_gms_lineEditMSLogin, 1, 1, 1, 1)
        self.tab_gms_msLoginStatus = QtWidgets.QLabel(self.groupBox_19)
        self.tab_gms_msLoginStatus.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tab_gms_msLoginStatus.setObjectName("tab_gms_msLoginStatus")
        self.gridLayout_44.addWidget(self.tab_gms_msLoginStatus, 4, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_19)
        self.label_73.setObjectName("label_73")
        self.gridLayout_44.addWidget(self.label_73, 1, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_19)
        self.label_74.setObjectName("label_74")
        self.gridLayout_44.addWidget(self.label_74, 2, 0, 1, 1)
        self.tab_gms_btnMSLogin = QtWidgets.QPushButton(self.groupBox_19)
        self.tab_gms_btnMSLogin.setObjectName("tab_gms_btnMSLogin")
        self.gridLayout_44.addWidget(self.tab_gms_btnMSLogin, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_44.addWidget(self.label_10, 0, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_44.addItem(spacerItem6, 5, 1, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_19, 0, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_45.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_45.setSpacing(6)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.tab_gms_cbFdr = QtWidgets.QComboBox(self.groupBox_20)
        self.tab_gms_cbFdr.setObjectName("tab_gms_cbFdr")
        self.tab_gms_cbFdr.addItem("")
        self.tab_gms_cbFdr.addItem("")
        self.tab_gms_cbFdr.addItem("")
        self.gridLayout_45.addWidget(self.tab_gms_cbFdr, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_20)
        self.label_13.setObjectName("label_13")
        self.gridLayout_45.addWidget(self.label_13, 0, 0, 1, 1)
        self.tab_gms_lineEditMSDs = QtWidgets.QLineEdit(self.groupBox_20)
        self.tab_gms_lineEditMSDs.setObjectName("tab_gms_lineEditMSDs")
        self.gridLayout_45.addWidget(self.tab_gms_lineEditMSDs, 1, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_20)
        self.label_75.setObjectName("label_75")
        self.gridLayout_45.addWidget(self.label_75, 2, 0, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_46.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_45.addWidget(self.pushButton_46, 1, 1, 1, 1)
        self.tab_gms_lineEditMSDb = QtWidgets.QListWidget(self.groupBox_20)
        self.tab_gms_lineEditMSDb.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tab_gms_lineEditMSDb.setFlow(QtWidgets.QListView.TopToBottom)
        self.tab_gms_lineEditMSDb.setProperty("isWrapping", False)
        self.tab_gms_lineEditMSDb.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.tab_gms_lineEditMSDb.setViewMode(QtWidgets.QListView.ListMode)
        self.tab_gms_lineEditMSDb.setModelColumn(0)
        self.tab_gms_lineEditMSDb.setBatchSize(3)
        self.tab_gms_lineEditMSDb.setWordWrap(False)
        self.tab_gms_lineEditMSDb.setSelectionRectVisible(False)
        self.tab_gms_lineEditMSDb.setObjectName("tab_gms_lineEditMSDb")
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.tab_gms_lineEditMSDb.addItem(item)
        self.gridLayout_45.addWidget(self.tab_gms_lineEditMSDb, 3, 0, 1, 2)
        self.label_76 = QtWidgets.QLabel(self.groupBox_20)
        self.label_76.setObjectName("label_76")
        self.gridLayout_45.addWidget(self.label_76, 4, 0, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_47.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_45.addWidget(self.pushButton_47, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_45.addItem(spacerItem7, 6, 0, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_20, 0, 1, 2, 1)
        self.verticalLayout_29.addWidget(self.widget_13)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.tabWidget.addTab(self.grab_ms_data_tab, "")
        self.cell_segm_tab = QtWidgets.QWidget()
        self.cell_segm_tab.setObjectName("cell_segm_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cell_segm_tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setSpacing(6)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.label_77 = QtWidgets.QLabel(self.cell_segm_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setObjectName("label_77")
        self.gridLayout_46.addWidget(self.label_77, 0, 0, 1, 1)
        self.helpText_16 = QtWidgets.QTextEdit(self.cell_segm_tab)
        self.helpText_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_16.setObjectName("helpText_16")
        self.gridLayout_46.addWidget(self.helpText_16, 1, 0, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.cell_segm_tab)
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_47.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_47.setSpacing(6)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.groupBox_21 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox_21.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_53 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_53.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_53.setSpacing(6)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_53.addWidget(self.radioButton, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_21)
        self.label_19.setObjectName("label_19")
        self.gridLayout_53.addWidget(self.label_19, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditCPpipeFile = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEditCPpipeFile.setObjectName("lineEditCPpipeFile")
        self.horizontalLayout.addWidget(self.lineEditCPpipeFile)
        self.btnCpPipeFile = QtWidgets.QToolButton(self.groupBox_21)
        self.btnCpPipeFile.setObjectName("btnCpPipeFile")
        self.horizontalLayout.addWidget(self.btnCpPipeFile)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton_15.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.gridLayout_53.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_53.addWidget(self.radioButton_2, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_21)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton_12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.gridLayout_53.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_21, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_47.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_46.addWidget(self.widget_14, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_46)
        self.tabWidget.addTab(self.cell_segm_tab, "")
        self.csv_gen_tab = QtWidgets.QWidget()
        self.csv_gen_tab.setObjectName("csv_gen_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.csv_gen_tab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_48 = QtWidgets.QGridLayout()
        self.gridLayout_48.setSpacing(6)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.helpText_17 = QtWidgets.QTextEdit(self.csv_gen_tab)
        self.helpText_17.setMaximumSize(QtCore.QSize(16777215, 100))
        self.helpText_17.setObjectName("helpText_17")
        self.gridLayout_48.addWidget(self.helpText_17, 1, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.csv_gen_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_79.sizePolicy().hasHeightForWidth())
        self.label_79.setSizePolicy(sizePolicy)
        self.label_79.setObjectName("label_79")
        self.gridLayout_48.addWidget(self.label_79, 0, 0, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.csv_gen_tab)
        self.widget_15.setMaximumSize(QtCore.QSize(555555, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_57.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_57.setSpacing(6)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.label_15 = QtWidgets.QLabel(self.widget_15)
        self.label_15.setObjectName("label_15")
        self.gridLayout_57.addWidget(self.label_15, 0, 0, 1, 1)
        self.tab_csvGen_corrValThr = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.tab_csvGen_corrValThr.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tab_csvGen_corrValThr.setFrame(False)
        self.tab_csvGen_corrValThr.setReadOnly(False)
        self.tab_csvGen_corrValThr.setAccelerated(False)
        self.tab_csvGen_corrValThr.setKeyboardTracking(False)
        self.tab_csvGen_corrValThr.setProperty("showGroupSeparator", False)
        self.tab_csvGen_corrValThr.setDecimals(2)
        self.tab_csvGen_corrValThr.setMinimum(0.0)
        self.tab_csvGen_corrValThr.setMaximum(1.0)
        self.tab_csvGen_corrValThr.setSingleStep(0.01)
        self.tab_csvGen_corrValThr.setProperty("value", 0.8)
        self.tab_csvGen_corrValThr.setObjectName("tab_csvGen_corrValThr")
        self.gridLayout_57.addWidget(self.tab_csvGen_corrValThr, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_15)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_14.setObjectName("label_14")
        self.gridLayout_57.addWidget(self.label_14, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tab_csvGen_lineEditCells = QtWidgets.QLineEdit(self.widget_15)
        self.tab_csvGen_lineEditCells.setObjectName("tab_csvGen_lineEditCells")
        self.horizontalLayout_4.addWidget(self.tab_csvGen_lineEditCells)
        self.tab_csvGen_btnCells = QtWidgets.QToolButton(self.widget_15)
        self.tab_csvGen_btnCells.setObjectName("tab_csvGen_btnCells")
        self.horizontalLayout_4.addWidget(self.tab_csvGen_btnCells)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.gridLayout_57.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_57.addItem(spacerItem9, 4, 1, 1, 1)
        self.gridLayout_48.addWidget(self.widget_15, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_48)
        self.tabWidget.addTab(self.csv_gen_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.btnRunNextStep = QtWidgets.QPushButton(self.centralWidget)
        self.btnRunNextStep.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnRunNextStep.setObjectName("btnRunNextStep")
        self.gridLayout.addWidget(self.btnRunNextStep, 4, 0, 1, 1)
        self.btnStartAnalysis = QtWidgets.QPushButton(self.centralWidget)
        self.btnStartAnalysis.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnStartAnalysis.setObjectName("btnStartAnalysis")
        self.gridLayout.addWidget(self.btnStartAnalysis, 5, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 2)
        self.btnSaveSettings = QtWidgets.QPushButton(self.centralWidget)
        self.btnSaveSettings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnSaveSettings.setObjectName("btnSaveSettings")
        self.gridLayout.addWidget(self.btnSaveSettings, 2, 0, 1, 1)
        self.LogsTextBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.LogsTextBrowser.setMaximumSize(QtCore.QSize(16777215, 1111))
        self.LogsTextBrowser.setObjectName("LogsTextBrowser")
        self.gridLayout.addWidget(self.LogsTextBrowser, 1, 1, 5, 1)
        self.gridLayout_11.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1093, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuSd = QtWidgets.QMenu(self.menuBar)
        self.menuSd.setObjectName("menuSd")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport_settings = QtWidgets.QAction(MainWindow)
        self.actionImport_settings.setObjectName("actionImport_settings")
        self.menuSd.addAction(self.actionImport_settings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuSd.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tab_gms_lineEditMSDb.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "spaceM 0.1"))
        self.btnRepeatStep.setText(_translate("MainWindow", "Repeat previous step"))
        self.btnImprtSettings.setText(_translate("MainWindow", "Import settings"))
        self.label.setText(_translate("MainWindow", "Help:"))
        self.helpText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is an example text that will be substituted with a custom step dependent explanotary information. For general setting, user has to provide all necessary paths to Main folder to where to store the output files, path to Python interpreter(ver&gt;3), and select stitched image with cell Profiler installed path.</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "General settings"))
        self.label_6.setText(_translate("MainWindow", "Cell Profiler path(Windows only):"))
        self.label_4.setText(_translate("MainWindow", "Python interpreter:"))
        self.label_3.setText(_translate("MainWindow", "Main Folder:"))
        self.btnCellProfiler.setText(_translate("MainWindow", "..."))
        self.btnPython.setText(_translate("MainWindow", "..."))
        self.btnMainFolder.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "?"))
        self.pushButton_6.setText(_translate("MainWindow", "?"))
        self.pushButton_8.setText(_translate("MainWindow", "?"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Pre/Post MALDI images"))
        self.btnStitchedPostMBfImg.setText(_translate("MainWindow", "..."))
        self.btnStitchedPreMBfImg.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "Stitched Post MALDI brightfield mage:"))
        self.label_8.setText(_translate("MainWindow", "Stitched Pre MALDI brightfield image:"))
        self.pushButton_3.setText(_translate("MainWindow", "?"))
        self.pushButton_2.setText(_translate("MainWindow", "?"))
        self.groupBox_3.setTitle(_translate("MainWindow", "MALDI data"))
        self.btnMALDImetadata.setText(_translate("MainWindow", "..."))
        self.pushButton_4.setText(_translate("MainWindow", "?"))
        self.label_12.setText(_translate("MainWindow", "Post Maldi microscopy metadata file:"))
        self.btnUdpFile.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "UDP file:"))
        self.pushButton_7.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gen_settings), _translate("MainWindow", "General settings"))
        self.helpText_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ablation mark finder is the first step to find region with the ablation marks that is based on fast Fouirer transformation, image blurring in the frequency space and its dilation to get to know what are the parameters play with them and check the output.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Help:"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Region growing algorithm options"))
        self.label_9.setText(_translate("MainWindow", "Estimated size of ablation mark in um:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Matrix preparation type"))
        self.tab_amf_btnFluoCh.setText(_translate("MainWindow", "..."))
        self.tab_amf_labelFluoCh.setText(_translate("MainWindow", "Path to the fluoresence channel image:"))
        self.tab_amf_cbMatrix.setCurrentText(_translate("MainWindow", "DAN"))
        self.tab_amf_cbMatrix.setItemText(0, _translate("MainWindow", "DAN"))
        self.tab_amf_cbMatrix.setItemText(1, _translate("MainWindow", "DHB"))
        self.tab_amf_amDetect.setTitle(_translate("MainWindow", "Detection of ablation marks"))
        self.tab_amf_btniFFTimg.setText(_translate("MainWindow", "..."))
        self.pushButton_10.setText(_translate("MainWindow", "?"))
        self.tab_amf_autoFftRb.setText(_translate("MainWindow", "Authomated FFT"))
        self.label_20.setText(_translate("MainWindow", "Iterations:"))
        self.label_21.setText(_translate("MainWindow", "Gaussian blur sigma:"))
        self.tab_amf_manFftRb.setText(_translate("MainWindow", "Manually provide processed image:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.amf_tab), _translate("MainWindow", "Ablation mark finder"))
        self.helpText_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The fiducial/penmarks search step tries to find them on the brighfield pre and post maldi images. In a process you will be given with a pop up matplotlip window with detections. Your aim is to remove all &quot;off&quot; penmarks detection, leaving only penmarks as much as possible. </p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Help:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fids_tab), _translate("MainWindow", "Fiducials search"))
        self.helpText_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Help:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reg_tab), _translate("MainWindow", "Registration"))
        self.label_72.setText(_translate("MainWindow", "Help:"))
        self.helpText_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Metaspace login"))
        self.pushButton_44.setText(_translate("MainWindow", "?"))
        self.tab_gms_msLoginStatus.setText(_translate("MainWindow", "[Status]"))
        self.label_73.setText(_translate("MainWindow", "Login:"))
        self.label_74.setText(_translate("MainWindow", "Password:"))
        self.tab_gms_btnMSLogin.setText(_translate("MainWindow", "Login"))
        self.label_10.setText(_translate("MainWindow", "Caution: for the private datasetes you have to log in first"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Data settings:"))
        self.tab_gms_cbFdr.setItemText(0, _translate("MainWindow", "10%"))
        self.tab_gms_cbFdr.setItemText(1, _translate("MainWindow", "20%"))
        self.tab_gms_cbFdr.setItemText(2, _translate("MainWindow", "50%"))
        self.label_13.setText(_translate("MainWindow", "Dataset name on metaspace:"))
        self.label_75.setText(_translate("MainWindow", "Database:"))
        self.pushButton_46.setText(_translate("MainWindow", "?"))
        self.tab_gms_lineEditMSDb.setSortingEnabled(True)
        __sortingEnabled = self.tab_gms_lineEditMSDb.isSortingEnabled()
        self.tab_gms_lineEditMSDb.setSortingEnabled(False)
        item = self.tab_gms_lineEditMSDb.item(0)
        item.setText(_translate("MainWindow", "HMDB-v4"))
        item = self.tab_gms_lineEditMSDb.item(1)
        item.setText(_translate("MainWindow", "BraChemDB-2018-01"))
        item = self.tab_gms_lineEditMSDb.item(2)
        item.setText(_translate("MainWindow", "Chebi-2018-1"))
        item = self.tab_gms_lineEditMSDb.item(3)
        item.setText(_translate("MainWindow", "LipidMaps-2017-12-12"))
        item = self.tab_gms_lineEditMSDb.item(4)
        item.setText(_translate("MainWindow", "PAMDB-v1.0"))
        item = self.tab_gms_lineEditMSDb.item(5)
        item.setText(_translate("MainWindow", "SwissLipids-2018-02-02"))
        item = self.tab_gms_lineEditMSDb.item(6)
        item.setText(_translate("MainWindow", "HMDB-v4-cotton"))
        item = self.tab_gms_lineEditMSDb.item(7)
        item.setText(_translate("MainWindow", "HMDB-v4-dev"))
        item = self.tab_gms_lineEditMSDb.item(8)
        item.setText(_translate("MainWindow", "HMDB-v4-endogenous"))
        item = self.tab_gms_lineEditMSDb.item(9)
        item.setText(_translate("MainWindow", "HMDB-v2.5"))
        self.tab_gms_lineEditMSDb.setSortingEnabled(__sortingEnabled)
        self.label_76.setText(_translate("MainWindow", "FDR:"))
        self.pushButton_47.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.grab_ms_data_tab), _translate("MainWindow", "Grab MS data"))
        self.label_77.setText(_translate("MainWindow", "Help:"))
        self.helpText_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Cell segmentation options:"))
        self.radioButton.setText(_translate("MainWindow", "Cells segmentation with Cellprofiler"))
        self.label_19.setText(_translate("MainWindow", "(Optional) Cellprofiler pipeline file:"))
        self.btnCpPipeFile.setText(_translate("MainWindow", "..."))
        self.pushButton_15.setText(_translate("MainWindow", "?"))
        self.radioButton_2.setText(_translate("MainWindow", "Manually provide Labeled cells TIFF image (! Not implemented!)"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.pushButton_12.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cell_segm_tab), _translate("MainWindow", "Cell segmentation"))
        self.helpText_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_79.setText(_translate("MainWindow", "Help:"))
        self.label_15.setText(_translate("MainWindow", "Distance correlation threshold:"))
        self.label_14.setText(_translate("MainWindow", "Cells morphological features csv file:"))
        self.tab_csvGen_btnCells.setText(_translate("MainWindow", "..."))
        self.pushButton_11.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.csv_gen_tab), _translate("MainWindow", "CSV generation"))
        self.btnRunNextStep.setText(_translate("MainWindow", "Run next step"))
        self.btnStartAnalysis.setText(_translate("MainWindow", "Run pipeline"))
        self.btnSaveSettings.setText(_translate("MainWindow", "Save settings"))
        self.LogsTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logs</p></body></html>"))
        self.menuSd.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionImport_settings.setText(_translate("MainWindow", "Import settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

